safe: true
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'serve.sh', 'article.png', 'LICENSE']
baseurl: /paper-now-chrjs
imports:
    - https://onecodex.github.io/research-article/components/research-article/research-article.html
collections:
    figures:
        output: true
        title: 'Figures'
    tables:
        output: true
        title: 'Tables'
    sections:
        output: true
